### ISSUE TITLE
no documentation

### ISSUE THREAD

**Issue by titaniumbones** [herewithme/simple-taxonomy#1]
Hello,

Im having a problem wiht rewrite slugs on one taxonomy and it's very difficult for me to figure out how to fix it.  If there were some documentation I'd be so grateful! Thanks.

**Comment by herewithme** [comment]
It is difficult to provide documentation for a plugin that has no API and no function for the theme.
This plugin just allows declare new taxonomies using the WordPress administration console.

About your problem, it's a bug, a documentation would probably not help.
It is also fixed in version 3.4.1
