### ISSUE TITLE
Function create_function() is deprecated

### ISSUE THREAD

**Issue by longnha** [herewithme/simple-taxonomy#9]
Hi,

Error on PHP7.2:

Deprecated: Function create_function() is deprecated in /wp-content/plugins/simple-taxonomy/simple-taxonomy.php on line 83

How can this be fixed please?

Thank you.

**Comment by jhume** [comment]
On line 83 of simple-taxonomy.php:

Change this:
	`add_action( 'widgets_init', create_function('', 'return register_widget("SimpleTaxonomy_Widget");') );`

To this:

`add_action( 'widgets_init', function() { return register_widget("SimpleTaxonomy_Widget"); });`
